osx_image: xcode61
language: objective-c
env:
  global:
    secure: "WCW/8qlLgH94wxvF86DrfBgzhAKFRtMIEBfj3bDWk8I1GUNkzUpU6Mya4zIgKS/WRVT31j5sVj4Do/9z2ffREnlAcWZPIurzyOm6IcJygVQN6uRlbI6m9J2L2WLu8W2XXQyYGIoEWMvznYZ9raY12QFnM+3LIvYFBckNZFhBUZA="
cache:
  - bundler
  - cocoapods
env:
  - UPLOAD_IOS_SNAPSHOT_BUCKET_NAME=eigen-ci UPLOAD_IOS_SNAPSHOT_BUCKET_PREFIX=snapshots

before_install:
  - 'echo ''gem: --no-ri --no-rdoc'' > ~/.gemrc'
  
  - echo "machine github.com login $GITHUB_API_KEY" > ~/.netrc
  - chmod 600 .netrc
  - pod repo add artsy https://github.com/artsy/Specs.git

install:
  - bundle install
  - make pods

before_script:
  - make ci

script:
  - make test
  - make lint

notifications:
  slack: 
    secure: "fXmNnx6XW5OvT/j2jSSHYd3mHwbL+GzUSUSWmZVT0Vx/Ga5jXINTOYRY/9PYgJMqdL8a/L0Mf/18ZZ+tliPlWQ/DnfTz1a3Q/Pf94hfYSGhSGlQC/eXYcpOm/dNOKYQ3sr4tqXtTPylPUDXHeiM2D59ggdlUvVwcALGgHizajPQ="
